/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
/* Header for class T */
#define  BUFSIZE 100
/*
 * Class:     T
 * Method:    sendMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_T_sendMessage
	(JNIEnv *env, jobject t)
{
	char buf[BUFSIZE]={0};
	sprintf(buf, "Hello, I am from buf array!\n");
	return (*env)->NewStringUTF(env, buf);
}

/*
 * Class:     T
 * Method:    changeMessage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_T_changeMessage
  (JNIEnv *env, jobject t, jstring mjString)
{
	char buf[BUFSIZE]={0};
	char* c_str;
	//从inString字符串取得指向字符串UTF编码的指针
	c_str = (*env)->GetStringUTFChars(env, mjString, JNI_FALSE);
	printf("Hello, I get the '%s' message and will change it!!\n",c_str);
	sprintf(buf, "-----change string is %s over----------",c_str);
	//通知本地虚拟机本机代码不再需要通过str访问java字符串
	(*env)->ReleaseStringUTFChars(env, mjString, (const char *)c_str);
	return (*env)->NewStringUTF(env, buf);
}
