/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class T */

#ifndef _Included_T
#define _Included_T
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     T
 * Method:    sendMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_T_sendMessage
  (JNIEnv *, jobject);

/*
 * Class:     T
 * Method:    changeMessage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_T_changeMessage
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
